"""add clear chat support (dm_clears table, group_members.cleared_at)

Revision ID: 1c85fb6cd6f5
Revises: d4436a13bc4d
Create Date: 2026-08-10 23:23:45.723157

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1c85fb6cd6f5'
down_revision: Union[str, Sequence[str], None] = 'd4436a13bc4d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dm_clears',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('other_user_id', sa.UUID(), nullable=False),
    sa.Column('cleared_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['other_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'other_user_id', name='uq_dm_clears_user_other')
    )
    op.create_index(op.f('ix_dm_clears_other_user_id'), 'dm_clears', ['other_user_id'], unique=False)
    op.create_index(op.f('ix_dm_clears_user_id'), 'dm_clears', ['user_id'], unique=False)
    op.add_column('group_members', sa.Column('cleared_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('group_members', 'cleared_at')
    op.drop_index(op.f('ix_dm_clears_user_id'), table_name='dm_clears')
    op.drop_index(op.f('ix_dm_clears_other_user_id'), table_name='dm_clears')
    op.drop_table('dm_clears')
    # ### end Alembic commands ###
