"""add join_policy to events

Revision ID: 6f2db3dd3caf
Revises: 66ff32903269
Create Date: 2026-08-10 17:45:33.064954

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6f2db3dd3caf'
down_revision: Union[str, Sequence[str], None] = '66ff32903269'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('join_policy', sa.String(length=30), server_default='open', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'join_policy')
    # ### end Alembic commands ###
