"""add unique username to users

Revision ID: 7e9723a12a78
Revises: 980619b90e13
Create Date: 2026-08-09 01:07:08.835694

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7e9723a12a78'
down_revision: Union[str, Sequence[str], None] = '980619b90e13'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Nullable first so this doesn't fail against existing rows, then
    # backfill from email, then tighten to NOT NULL. Backfill assumes no
    # two existing rows share an email local-part — true for our current
    # dev data; a real production migration would need a proper
    # dedup/suffix loop like app.core.username.generate_unique_username.
    op.add_column('users', sa.Column('username', sa.String(length=30), nullable=True))
    op.execute(
        "UPDATE users SET username = lower(regexp_replace(split_part(email, '@', 1), '[^a-zA-Z0-9_]', '_', 'g'))"
    )
    op.alter_column('users', 'username', nullable=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_column('users', 'username')
    # ### end Alembic commands ###
