"""add tags and user location/onboarding fields

Revision ID: 980619b90e13
Revises: 71732379d555
Create Date: 2026-08-08 23:14:23.642597

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '980619b90e13'
down_revision: Union[str, Sequence[str], None] = '71732379d555'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tags',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tags_slug'), 'tags', ['slug'], unique=True)
    op.create_table('user_tags',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('tag_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'tag_id')
    )
    op.add_column('users', sa.Column('location_lat', sa.Float(), nullable=True))
    op.add_column('users', sa.Column('location_lng', sa.Float(), nullable=True))
    op.add_column('users', sa.Column('location_label', sa.String(length=255), nullable=True))
    # server_default needed here (not just the ORM-level default) so this
    # NOT NULL column can be added to a table that may already have rows.
    op.add_column(
        'users',
        sa.Column('onboarding_completed', sa.Boolean(), nullable=False, server_default=sa.false()),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'onboarding_completed')
    op.drop_column('users', 'location_label')
    op.drop_column('users', 'location_lng')
    op.drop_column('users', 'location_lat')
    op.drop_table('user_tags')
    op.drop_index(op.f('ix_tags_slug'), table_name='tags')
    op.drop_table('tags')
    # ### end Alembic commands ###
