"""replace event category tags with fixed single-select fields

Revision ID: c316b7ae0c54
Revises: 6f2db3dd3caf
Create Date: 2026-08-10 17:58:39.571051

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c316b7ae0c54'
down_revision: Union[str, Sequence[str], None] = '6f2db3dd3caf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('event_tags')
    op.add_column('events', sa.Column('activity_type', sa.String(length=50), nullable=True))
    op.add_column('events', sa.Column('community_vibe', sa.String(length=50), nullable=True))
    op.add_column('events', sa.Column('skill_level', sa.String(length=50), nullable=True))
    op.add_column('events', sa.Column('event_style', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'event_style')
    op.drop_column('events', 'skill_level')
    op.drop_column('events', 'community_vibe')
    op.drop_column('events', 'activity_type')
    op.create_table('event_tags',
    sa.Column('event_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('tag_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], name=op.f('event_tags_event_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], name=op.f('event_tags_tag_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('event_id', 'tag_id', name=op.f('event_tags_pkey'))
    )
    # ### end Alembic commands ###
