"""add dm_mutes table

Revision ID: c7c8810c888b
Revises: dd53fe4f5d2e
Create Date: 2026-08-15 00:21:20.135763

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c7c8810c888b'
down_revision: Union[str, Sequence[str], None] = 'dd53fe4f5d2e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dm_mutes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('other_user_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['other_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'other_user_id', name='uq_dm_mutes_user_other')
    )
    op.create_index(op.f('ix_dm_mutes_other_user_id'), 'dm_mutes', ['other_user_id'], unique=False)
    op.create_index(op.f('ix_dm_mutes_user_id'), 'dm_mutes', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_dm_mutes_user_id'), table_name='dm_mutes')
    op.drop_index(op.f('ix_dm_mutes_other_user_id'), table_name='dm_mutes')
    op.drop_table('dm_mutes')
    # ### end Alembic commands ###
