"""add avatar_url to chat_groups

Revision ID: d4436a13bc4d
Revises: 8c5dd7ef4e11
Create Date: 2026-08-10 22:30:18.889035

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd4436a13bc4d'
down_revision: Union[str, Sequence[str], None] = '8c5dd7ef4e11'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_groups', sa.Column('avatar_url', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat_groups', 'avatar_url')
    # ### end Alembic commands ###
