"""add bio and gender to users

Revision ID: f1d15efda4ff
Revises: 7e9723a12a78
Create Date: 2026-08-09 01:24:59.457090

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f1d15efda4ff'
down_revision: Union[str, Sequence[str], None] = '7e9723a12a78'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('bio', sa.String(length=150), nullable=True))
    op.add_column('users', sa.Column('gender', sa.String(length=30), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'gender')
    op.drop_column('users', 'bio')
    # ### end Alembic commands ###
